version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_1_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - symfony

  db:
    image: postgres:16-alpine
    container_name: symfony_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony_test
    ports:
      - "5432:5432"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

